# Generated by Django 2.2 on 2020-08-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMaterial', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=30)),
                ('año', models.IntegerField()),
                ('status', models.CharField(choices=[('IN', 'En biblioteca'), ('BW', 'Prestado'), ('RQ', 'Pedido'), ('RV', 'Reservado')], default='En biblioteca', max_length=2)),
            ],
        ),
    ]
