# Generated by Django 2.2 on 2020-08-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material de Lectura', 'verbose_name_plural': 'Materiales de Lectura'},
        ),
    ]
