# Generated by Django 2.2 on 2020-08-18 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0002_auto_20200814_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Biblioteca.Material')),
                ('editorial', models.CharField(max_length=40)),
            ],
            bases=('Biblioteca.material',),
        ),
    ]
