# Generated by Django 2.2 on 2020-08-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0003_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Biblioteca.Material')),
            ],
            options={
                'verbose_name': 'Revista',
                'verbose_name_plural': 'Revistas',
            },
            bases=('Biblioteca.material',),
        ),
        migrations.RemoveField(
            model_name='material',
            name='tipoMaterial',
        ),
    ]
