# Generated by Django 2.2 on 2020-08-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0004_auto_20200819_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('numero', models.IntegerField()),
                ('num_libros', models.IntegerField()),
                ('deuda', models.BooleanField()),
            ],
        ),
    ]
