# Generated by Django 2.2 on 2020-08-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0006_alumno_profesor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
