# Generated by Django 2.2 on 2020-08-19 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0007_auto_20200819_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.Material')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.Persona')),
            ],
        ),
    ]
