# Generated by Django 2.2 on 2020-08-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0008_prestamo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revista',
            options={},
        ),
        migrations.AlterField(
            model_name='persona',
            name='deuda',
            field=models.FloatField(),
        ),
    ]
