# Generated by Django 2.2 on 2020-08-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0009_auto_20200819_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='numero',
            new_name='telefono',
        ),
    ]
