# Generated by Django 2.2 on 2020-08-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0010_auto_20200819_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fotoPortada',
            field=models.ImageField(blank=True, upload_to='portadas/'),
        ),
    ]
